### PR TITLE
Added baseline groups

### PR DESCRIPTION
**Pull request by jvalteren**
Added default and Tests groups to allow projects to exclude loading tests.

### CODE REVIEW

**Comment by jvalteren** [comment]
Ah, I see I didn't take the CI into account. Will look into that soon and (try to) fix that for the PR.

**Comment by jecisc** [comment]
Personally, I would let the tests in the default group but I would create a `Core` and `Tests` group. 

Core would be your current default and Tests would be your current Tests group.

**Comment by jvalteren** [comment]
Ah yes, thanks for getting back on this! I will modify the baseline.

I am used to working with GitLab, which allows updates to open pull requests. Don't know if GitHub allows that as well. Otherwise I'll create a new pull request.

Thanks!

**Comment by jecisc** [comment]
If you push to your branch the PR will be updated as long as it is open

**Comment by jecisc** [comment]
Thank you!

I'll soon create a release with you change.

**Comment by jecisc** [comment]
https://github.com/pharo-contributions/OSSubprocess/releases/tag/v1.1.1

**Comment by jvalteren** [comment]
Ah thanks, I didn't know the 'default' group would be present without specifying it.
Thanks for taking the time to pick this up!

**Comment by jecisc** [comment]
The default group exists by default and will load everything present in the baseline (package, group, dependency).

When you load without specifying a group, it will load #default. 

You can override it, but if it's to include everything it's better to not change it so that if we add something in the future it will be included in the default group.

See: https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/Baselines.md#the-default-group

**Pull request merged**
